### ISSUE TITLE
Student(s) -- allow self registration

### ISSUE THREAD

**Issue by odyright** [digitalnatives/course_planner#184]
Firstly, i want to great to for your project @ggpasqualino . 

the `resources "/students", StudentController` is protected that's fine, but Now I want to expose some fact: what about if we want to allow student registering himself/herself? how the code will look like?

for automatic enrollment/registration....instead of doing it by the admin's folk...
it'll be good.

**Comment by ghatighorias** [comment]
I think this can be a system setting that can be activated by the admin. 
ALLOW_SELF_REGISTRATION ( of type boolean ).

@ggpasqualino @rhnonose what do you guys think about it ?

**Comment by rhnonose** [comment]
We removed the `:registerable` option from coherence, but it's not that hard to put it back.

**Comment by ghatighorias** [comment]
hmm @rhnonose i might be a bit lost. I assumed that the self-registration is for offered_courses :P
and not to the system. but even if the that be the case there is now a bigger problem and is to assign a student to a specific term, so S/he can register just for the courses of that term

**Comment by rhnonose** [comment]
@ghatighorias I assumed it was for someone that doesn't have an account because he mentioned protected routes.
But for the other, makes sense to have an attribute in the `offered_course` to allow subscription (or another approach maybe).

**Comment by odyright** [comment]
thank you for your reply @ghatighorias @rhnonose , in my opinon the coherence `:registerable` must concern the Admin system's part and don't expose it.

1.  when the Admin is logged in/registered.... S/he can achieve administrative tasks (create students, course, calender, etc.) that's is allowed like:

```elixir
scope "/", CoursePlanner do
    pipe_through :protected

    .......

    resources "/users", UserController, except: [:create, :new]
    .....
    resources "/students", StudentController
    resources "/teachers", TeacherController
    resources "/volunteers", VolunteerController

    resources "/courses", CourseController
    ......
    resources "/tasks", TaskController do
      post "/grab", TaskController, :grab, as: :grab
      post "/drop", TaskController, :drop, as: :drop
    end
    .......
    
  end
```

2. In the mentioned case earlier if we want to allow student registering himself/herself , we can use `pipe_through :public` or `pipe_through :browser`  instead of `pipe_through :protected`

```elixir
scope "/", CoursePlanner do
    pipe_through :public # or pipe_through :browser

    resources "/students", StudentController  only [:new, :create, :show]
  end
```
and then define the **plug :public** i'm not sure but it could be improved...

```elixir
defp public(conn, _) do
    if conn.assigns[:current_user] do
      conn
        |> Phoenix.Controller.put_flash(:success, "You're in!")
        |> Phoenix.Controller.redirect(to: .....student_path...(conn, :show)
        |> halt()
     else
        conn
        |> Phoenix.Controller.redirect(to: .....student_path...(conn, [:create, :show])
    end
  end
```

**Comment by rhnonose** [comment]
Yeah, that makes sense. We'll consider that option.
Thank you, @odyright

**Comment by ggpasqualino** [comment]
Hey @odyright thanks for your interest :)

So, the reason we didn't add that so far is that in our use case a student should go through some tests or interviews before being added to the system.

We have in our backlog a feature to add an application form where students can apply to the program, but maybe that wouldn't cover your use case.

Anyways, we can think about some configurable way to do it

**Comment by odyright** [comment]
hey @ggpasqualino 

> We have in our backlog a feature to add an application form where students can apply to the program, but maybe that wouldn't cover your use case.

Is the application form parts of this repo? if yes i'm interested..!

**Comment by ggpasqualino** [comment]
@odyright not yet, this is a bit low priority for now

**Comment by odyright** [comment]
ok!
